Backend/parts&orders
Szcz3sny/DBMS_Project pull request #5
Opened 2023-12-10 22:48 UTC by gkrzysztof

2024-01-07 21:45 UTC, flkrystian requested changes

2024-01-07 21:45 UTC, flkrystian commented on car-workshop-backend/src/main/kotlin/bazydanych/model/Orders.kt
> +    val Id_Parts: Int,
partId

2024-01-07 21:45 UTC, flkrystian commented on car-workshop-backend/src/main/kotlin/bazydanych/model/Orders.kt
> +    val Status: String,
status

2024-01-07 21:45 UTC, flkrystian commented on car-workshop-backend/src/main/kotlin/bazydanych/service/form/PartsCreateForm.kt
> +    val product_name: String,
camelCase

2024-01-08 06:53 UTC, flkrystian approved these changes

2024-01-08 06:54 UTC, gkrzysztof commented
mamy to

2024-01-08 06:54 UTC, merged